# Generated by Django 5.2.5 on 2025-08-22 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100)),
                ("added_date", models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Dishes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dish_name", models.CharField(max_length=150)),
                ("receipe", models.TextField()),
                ("price", models.IntegerField()),
                (
                    "optional",
                    models.CharField(
                        choices=[("SG", "Signature")], max_length=100, null=True
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Order.categories",
                    ),
                ),
            ],
        ),
    ]
