# Generated by Django 5.2.5 on 2025-08-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishes",
            name="optional",
            field=models.CharField(
                blank=True, choices=[("SG", "Signature")], max_length=100, null=True
            ),
        ),
    ]
