# Generated by Django 5.2.5 on 2025-08-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0002_alter_dishes_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishes",
            name="optional",
            field=models.CharField(
                blank=True,
                choices=[("SG", "Signature"), ("SP", "Spicy"), ("SP", "Special")],
                max_length=100,
                null=True,
            ),
        ),
    ]
