# Generated by Django 5.2.5 on 2025-08-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0003_alter_dishes_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishes",
            name="receipe",
            field=models.TextField(blank=True, null=True),
        ),
    ]
