# Generated by Django 5.2.5 on 2025-08-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0004_alter_dishes_receipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="dishes",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
