# Generated by Django 5.2.5 on 2025-08-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0005_dishes_is_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="dishes",
            name="dish_image",
            field=models.ImageField(blank=True, null=True, upload_to="Images"),
        ),
    ]
