# Generated by Django 5.2.5 on 2025-09-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0007_alter_dishes_dish_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishes",
            name="dish_image",
            field=models.ImageField(
                blank=True, default="Images/default.png", null=True, upload_to="Images"
            ),
        ),
    ]
