# Generated by Django 5.2.5 on 2025-09-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='taxAmt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
