# Generated by Django 5.2.5 on 2025-09-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Billing", "0002_bill_taxamt"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashier",
            name="email",
            field=models.EmailField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="cashier",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
