# Generated by Django 5.2.5 on 2025-09-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Billing", "0003_cashier_email_cashier_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashier",
            name="email",
            field=models.EmailField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="cashier",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
