# Generated by Django 5.2.5 on 2026-05-01 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0004_alter_cashier_email_alter_cashier_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('Modify', 'Modify'), ('Delete', 'Delete')], max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Billing.bill')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Billing.cashier')),
            ],
        ),
    ]
